# Generated by Django 3.0.7 on 2020-08-02 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_number', models.IntegerField()),
                ('street_name', models.CharField(max_length=40)),
                ('postal_code', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=40)),
                ('country', models.CharField(max_length=40)),
                ('number_of_units', models.IntegerField(blank=True, null=True)),
                ('number_of_floors', models.IntegerField()),
                ('surface_area', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('ownerName', models.CharField(blank=True, max_length=30, null=True)),
                ('construction_date', models.DateField(blank=True, null=True)),
                ('acquisition_date', models.DateField(blank=True, null=True)),
                ('acquisition_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('is_co_ownership', models.BooleanField()),
                ('is_in_protected_heritage_area', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('ap', 'Appartment'), ('ho', 'House')], max_length=2)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('position', models.CharField(blank=True, choices=[('le', 'Left'), ('ri', 'Right'), ('ce', 'Center'), ('cl', 'Center Left'), ('cr', 'Center Right')], max_length=2, null=True)),
                ('surface_area', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.Building')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ic', 'Insurance Compensation'), ('re', 'Rent'), ('ha', 'Housing Allowance'), ('ot', 'Other Payment')], max_length=2)),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('observations', models.CharField(blank=True, max_length=100, null=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.Building')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.Unit')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ta', 'Taxes'), ('wb', 'Water Bill'), ('eb', 'Electricity Bill'), ('ic', 'Insurance Cotisation'), ('af', 'Accountant Fees'), ('rf', 'Realtor Fees'), ('df', 'Diagnostician Fees'), ('lf', 'Legal Fees'), ('cf', 'Condo Fees'), ('or', 'Overpayment Refund')], max_length=2)),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('observations', models.CharField(blank=True, max_length=100, null=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.Building')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.Unit')),
            ],
        ),
    ]
