# Generated by Django 3.0.7 on 2020-06-11 06:28

import address.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0002_auto_20160213_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_in_protected_heritage_area', models.BooleanField()),
                ('construction_date', models.DateField(blank=True, null=True)),
                ('acquisition_date', models.DateField(blank=True, null=True)),
                ('acquisition_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_co_ownership', models.BooleanField()),
                ('address', address.models.AddressField(on_delete=django.db.models.deletion.CASCADE, to='address.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, choices=[('le', 'Left'), ('ri', 'Right'), ('ce', 'Center')], max_length=2, null=True)),
                ('property_type', models.CharField(choices=[('ap', 'Appartment'), ('ho', 'House')], max_length=2)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('is_occupied', models.BooleanField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.Building')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('re', 'Rent'), ('ha', 'Housing Allowance'), ('ot', 'Other Payment')], max_length=2)),
                ('currency', models.CharField(choices=[('eu', 'EUR'), ('us', 'USD'), ('jp', 'JPY'), ('gb', 'GBP'), ('au', 'AUD'), ('ca', 'CAD'), ('ch', 'CHF'), ('cn', 'CNY')], max_length=2)),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('observation', models.CharField(blank=True, max_length=100, null=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.Unit')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ta', 'Taxes'), ('wb', 'Water Bill'), ('eb', 'Electricity Bill'), ('ic', 'Insurance Cotisation'), ('af', 'Accountant Fees'), ('rf', 'Realtor Fees'), ('df', 'Diagnostician Fees'), ('lf', 'Legal Fees'), ('cf', 'Condo Fees'), ('or', 'Overpayment Refund')], max_length=2)),
                ('currency', models.CharField(choices=[('eu', 'EUR'), ('us', 'USD'), ('jp', 'JPY'), ('gb', 'GBP'), ('au', 'AUD'), ('ca', 'CAD'), ('ch', 'CHF'), ('cn', 'CNY')], max_length=2)),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('observation', models.CharField(blank=True, max_length=100, null=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.Building')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.Unit')),
            ],
        ),
    ]
