# Generated by Django 3.0.7 on 2020-08-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='street_number',
            field=models.CharField(max_length=10),
        ),
    ]
